import Navbar from "@/components/Navbar";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import "./styles/main.scss";
import ClientProvider from "../store/ClientProvider"; // Import ClientProvider

export const metadata = {
  title: "Olopo Business Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar></Navbar>
        </main>
        <main>
          <Sidebar />
          <ClientProvider>{children}</ClientProvider>
        </main>
      </body>
    </html>
  );
}
