import Navbar from "@/components/Navbar";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Olopo Business Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <main>
          <Navbar></Navbar></main>
        <main className="busntwrk__body">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
